import '../styles/Legal.css';

function TermsOfService() {
  return (
    <div className="legal-container">
      <h1>Terms of Service</h1>
      <p><strong>Last updated:</strong> May 20, 2025</p>

      <h2>Usage</h2>
      <p>You agree not to misuse the service or attempt to interfere with its functionality. You must be at least 13 years old to use MindHaven.</p>

      <h2>Content</h2>
      <p>While we aim to provide helpful and empathetic responses, all output from our AI should be viewed as informational only.</p>

      <h2>Limitation of Liability</h2>
      <p>MindHaven is not liable for any decisions or actions taken based on content generated by the AI.</p>
    </div>
  );
}

export default TermsOfService;
